version: '3.9'

services: 
  server-node:
    image: server-node
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
volumes:
  mongo_data: